In [1]:
import numpy as np

In [6]:
lis=[9,6,8,4]
np.array(lis)

array([9, 6, 8, 4])

In [3]:
mat=[(7,6,8),(6,5,3),(6,4,22)]
np.array(mat)

array([[ 7,  6,  8],
       [ 6,  5,  3],
       [ 6,  4, 22]])

In [8]:
np.arange(0,67,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64])

In [11]:
np.zeros((7,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.linspace(0,9,50)

array([0.        , 0.18367347, 0.36734694, 0.55102041, 0.73469388,
       0.91836735, 1.10204082, 1.28571429, 1.46938776, 1.65306122,
       1.83673469, 2.02040816, 2.20408163, 2.3877551 , 2.57142857,
       2.75510204, 2.93877551, 3.12244898, 3.30612245, 3.48979592,
       3.67346939, 3.85714286, 4.04081633, 4.2244898 , 4.40816327,
       4.59183673, 4.7755102 , 4.95918367, 5.14285714, 5.32653061,
       5.51020408, 5.69387755, 5.87755102, 6.06122449, 6.24489796,
       6.42857143, 6.6122449 , 6.79591837, 6.97959184, 7.16326531,
       7.34693878, 7.53061224, 7.71428571, 7.89795918, 8.08163265,
       8.26530612, 8.44897959, 8.63265306, 8.81632653, 9.        ])

identity

In [11]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
rando=np.random.randint(0,100,4)
rando

array([57, 39, 47, 87])

In [6]:
rando.max()

85

In [7]:
rando.argmax()

32

returns index value of max

In [9]:
rando.dtype

dtype('int64')

In [14]:
a=np.arange(0,44,2)
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42])

In [15]:
a[:3]

array([0, 2, 4])

In [16]:
a[::-1]

array([42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18, 16, 14, 12, 10,
        8,  6,  4,  2,  0])

In [27]:
a[1:7:2]

array([ 2,  6, 10])

In [29]:
a[9]=987
a

array([  0,   2,   4,   6,   8,  10,  12,  14,  16, 987,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42])

In [32]:
a_copy=a.copy()
a_copy[:]=999999
a_copy

array([999999, 999999, 999999, 999999, 999999, 999999, 999999, 999999,
       999999, 999999, 999999, 999999, 999999, 999999, 999999, 999999,
       999999, 999999, 999999, 999999, 999999, 999999])

In [34]:
bool_array=a>9
bool_array


array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [35]:
a[bool_array]

array([ 10,  12,  14,  16, 987,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42])

In [36]:
a[a<6]

array([0, 2, 4])

In [40]:
b_2d= np.arange(50).reshape(5,10)
b_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [48]:
b_2d[1:2,3:6]

array([[13, 14, 15]])

In [56]:
c=np.arange(0,16,2)
d=np.arange(18,26)

In [62]:
d+100
(d*c)/(d*c)

/home/shubhangi/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [63]:
1/c

/home/shubhangi/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 0.5       , 0.25      , 0.16666667, 0.125     ,
       0.1       , 0.08333333, 0.07142857])

In [64]:
d**2

array([324, 361, 400, 441, 484, 529, 576, 625])

In [66]:
np.sqrt(d**3)

array([ 76.36753237,  82.81907993,  89.4427191 ,  96.23408959,
       103.18914672, 110.30412504, 117.57550765, 125.        ])

In [67]:
np.log(c)

/home/shubhangi/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.69314718, 1.38629436, 1.79175947, 2.07944154,
       2.30258509, 2.48490665, 2.63905733])

In [17]:
a*2

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84])